// packages/react/src/App.jsx
import React from "react";
import BlossomCarousel from "./components/BlossomCarousel.jsx";

export default function App() {
  return (
    <div className="page">
      <h1>Blossom in React</h1>
      <BlossomCarousel as="ul" className="carousel">
        {Array.from({ length: 12 }, (_, i) => (
          <li key={`slide${i + 1}`} className="slide">
            {i + 1}
          </li>
        ))}
      </BlossomCarousel>
    </div>
  );
}

// packages/svelte/src/App.svelte
<script>
  import BlossomCarousel from './components/BlossomCarousel.svelte';
</script>

<div class="page">
    <h1>Blossom in Svelte</h1>  
    <BlossomCarousel as="ul" class="carousel">
        {#each Array(12).fill(0).map((_, i) => i + 1) as num}
            <li key={num} class="slide">{num}</li>
        {/each}
    </BlossomCarousel>
</div>
