// packages/react/src/BlossomDots.tsx
import React, { ReactNode } from "react";
import { COMMANDS } from "@blossom-carousel/navigation";
import { useNavigation } from "./useNavigation";

export interface BlossomDotsProps {
  for: string;
  children?: (props: { index: number; active: boolean }) => ReactNode;
}

export default function BlossomDots({ for: carouselId, children }: BlossomDotsProps) {
  const state = useNavigation(carouselId);

  return (
    <div className="blossom-dots" role="group" aria-label="Choose slide to display">
      {Array.from({ length: state.count }, (_, index) => (
        <button
          key={index}
          type="button"
          className="blossom-dot"
          command={`${COMMANDS.gotoPrefix}${index}`}
          commandfor={carouselId}
          aria-current={state.activeIndex === index ? "true" : undefined}
          aria-label={`Go to slide ${index + 1}`}
        >
          {children?.({ index, active: state.activeIndex === index })}
        </button>
      ))}
    </div>
  );
}

// packages/svelte/src/BlossomDots.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { COMMANDS } from "@blossom-carousel/navigation";
  import { createNavigationStore } from "./navigation";

  export let forId: string;

  const state = createNavigationStore();
  $: state.connect(forId);
  onDestroy(() => state.disconnect());
</script>

<div class="blossom-dots" role="group" aria-label="Choose slide to display">
  {#each Array.from({ length: $state.count }, (_, index) => index) as index (index)}
    <button
      type="button"
      class="blossom-dot"
      command="{COMMANDS.gotoPrefix}{index}"
      commandfor={forId}
      aria-current={$state.activeIndex === index ? "true" : undefined}
      aria-label="Go to slide {index + 1}"
    >
      <slot {index} active={$state.activeIndex === index} />
    </button>
  {/each}
</div>
