// packages/react/src/BlossomCarousel.tsx
import React, {
  ElementType,
  forwardRef,
  ReactNode,
  useEffect,
  useImperativeHandle,
  useRef,
  JSXElementConstructor,
} from "react";

export interface BlossomCarouselHandle {
  prev: (options?: { align?: string }) => void;
  next: (options?: { align?: string }) => void;
  element: HTMLElement | null;
}

export interface BlossomCarouselProps extends React.HTMLAttributes<HTMLElement> {
  children?: ReactNode | Array<ReactNode>;
  as?: ElementType;
  repeat?: boolean;
  load?: "always" | "conditional";
}

const BlossomCarousel = forwardRef<BlossomCarouselHandle, BlossomCarouselProps>(
  (
    { children, as = "div", repeat = false, load = "conditional", ...props },
    parentRef,
  ) => {
    const Component = as as JSXElementConstructor<any>;
    const localRef = useRef<HTMLElement>(null);
    const blossomRef = useRef<ReturnType<
      typeof import("@blossom-carousel/core").Blossom
    > | null>(null);

    useEffect(() => {
      if (!localRef.current) return;

      const hasMouse = window.matchMedia(
        "(hover: hover) and (pointer: fine)",
      ).matches;

      if (!hasMouse && load !== "always") return;

      let destroyed = false;

      import("@blossom-carousel/core").then(({ Blossom }) => {
        if (destroyed || !localRef.current) return;

        const blossom = Blossom(localRef.current, { repeat });
        blossomRef.current = blossom;
        blossom.init();
      });

      return () => {
        destroyed = true;
        blossomRef.current?.destroy();
        blossomRef.current = null;
      };
    }, [repeat, load]);

    useImperativeHandle(
      parentRef,
      () => ({
        prev: (options?: { align?: string }) =>
          blossomRef.current?.prev(options),
        next: (options?: { align?: string }) =>
          blossomRef.current?.next(options),
        element: localRef.current,
      }),
      [],
    );

    return (
      <Component ref={localRef} blossom-carousel="true" {...props}>
        {children}
      </Component>
    );
  },
);

BlossomCarousel.displayName = "BlossomCarousel";

export default BlossomCarousel;

// packages/svelte/src/BlossomCarousel.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { Blossom } from '@blossom-carousel/core';

  export let as: string = 'div';
  export let load: 'always' | 'conditional' = 'conditional';
  export let repeat: boolean = false;
  
  let root: HTMLElement;
  let blossom: ReturnType<typeof Blossom> | undefined;

  onMount(async () => {
    if (root) {
      const hasMouse = window.matchMedia("(hover: hover) and (pointer: fine)").matches;

      // don't load if the user has no mouse.
      // overwritten by props.load: 'always'
      if (!hasMouse && load !== "always") return;

      const { Blossom } = await import("@blossom-carousel/core");

      blossom = Blossom(root, { repeat });
      blossom.init();
    }
  });

  onDestroy(() => {
    blossom?.destroy();
  });

  export function prev(options?: { align?: string }) {
    blossom?.prev(options);
  }

  export function next(options?: { align?: string }) {
    blossom?.next(options);
  }
</script>

<svelte:element
  this={as}
  bind:this={root}
  blossom-carousel="true"
  {...$$restProps}
>
  <slot />
</svelte:element>
