// packages/svelte/dev/App.svelte
<script>
  import BlossomCarousel from "../src/BlossomCarousel.svelte";
  import BlossomPrev from "../src/BlossomPrev.svelte";
  import BlossomNext from "../src/BlossomNext.svelte";
  import BlossomDots from "../src/BlossomDots.svelte";
</script>

<div class="page">
  <h1>Blossom in Svelte</h1>
  <BlossomCarousel id="my-carousel" as="ul" class="carousel">
    {#each Array(12).fill(0).map((_, i) => i + 1) as num (num)}
      <li class="slide" data-blossom-slide>{num}</li>
    {/each}
  </BlossomCarousel>
  <div class="controls">
    <BlossomPrev forId="my-carousel" />
    <BlossomDots forId="my-carousel" />
    <BlossomNext forId="my-carousel" />
  </div>
</div>

// packages/react/src/App.tsx
import BlossomCarousel from "./BlossomCarousel";
import BlossomPrev from "./BlossomPrev";
import BlossomNext from "./BlossomNext";
import BlossomDots from "./BlossomDots";

export default function App() {
  return (
    <div className="page">
      <h1>Blossom in React</h1>
      <BlossomCarousel id="my-carousel" as="ul" className="carousel">
        {Array.from({ length: 12 }, (_, i) => (
          <li key={`slide${i + 1}`} className="slide" data-blossom-slide>
            {i + 1}
          </li>
        ))}
      </BlossomCarousel>
      <div className="controls">
        <BlossomPrev for="my-carousel" />
        <BlossomDots for="my-carousel" />
        <BlossomNext for="my-carousel" />
      </div>
    </div>
  );
}
