// packages/vue/src/BlossomNext.vue
<template>
  <button
    type="button"
    :command="command"
    :commandfor="props.for"
    :disabled="!state.canNext"
    aria-label="Next"
  >
    <slot>Next</slot>
  </button>
</template>

<script setup lang="ts">
import { toRef } from "vue";
import { COMMANDS } from "@blossom-carousel/navigation";
import { useNavigation } from "./useNavigation";

const props = defineProps<{ for: string }>();

const command = COMMANDS.next;
const state = useNavigation(toRef(props, "for"));
</script>

// packages/react/src/BlossomNext.tsx
import React, { ReactNode } from "react";
import { COMMANDS } from "@blossom-carousel/navigation";
import { useNavigation } from "./useNavigation";

export interface BlossomNextProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "children"> {
  for: string;
  children?: ReactNode;
}

export default function BlossomNext({
  for: carouselId,
  children = "Next",
  disabled,
  ...props
}: BlossomNextProps) {
  const state = useNavigation(carouselId);

  return (
    <button
      type="button"
      command={COMMANDS.next}
      commandfor={carouselId}
      disabled={disabled ?? !state.canNext}
      aria-label="Next"
      {...props}
    >
      {children}
    </button>
  );
}
