// packages/vue/src/BlossomPrev.vue
<template>
  <button
    type="button"
    :command="command"
    :commandfor="props.for"
    :disabled="!state.canPrev"
    aria-label="Previous"
  >
    <slot>Previous</slot>
  </button>
</template>

<script setup lang="ts">
import { toRef } from "vue";
import { COMMANDS } from "@blossom-carousel/navigation";
import { useNavigation } from "./useNavigation";

const props = defineProps<{ for: string }>();

const command = COMMANDS.prev;
const state = useNavigation(toRef(props, "for"));
</script>

// packages/react/src/BlossomPrev.tsx
import React, { ReactNode } from "react";
import { COMMANDS } from "@blossom-carousel/navigation";
import { useNavigation } from "./useNavigation";

export interface BlossomPrevProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "children"> {
  for: string;
  children?: ReactNode;
}

export default function BlossomPrev({
  for: carouselId,
  children = "Previous",
  disabled,
  ...props
}: BlossomPrevProps) {
  const state = useNavigation(carouselId);

  return (
    <button
      type="button"
      command={COMMANDS.prev}
      commandfor={carouselId}
      disabled={disabled ?? !state.canPrev}
      aria-label="Previous"
      {...props}
    >
      {children}
    </button>
  );
}
