// packages/svelte/dev/App.svelte
<script>
  import BlossomCarousel from "../src/BlossomCarousel.svelte";
  import BlossomPrev from "../src/BlossomPrev.svelte";
  import BlossomNext from "../src/BlossomNext.svelte";
  import BlossomDots from "../src/BlossomDots.svelte";
  import BlossomDot from "../src/BlossomDot.svelte";
</script>

<div class="page">
  <h1>Blossom in Svelte</h1>
  <BlossomCarousel id="my-carousel" as="ul" class="carousel">
    {#each Array(12).fill(0).map((_, i) => i + 1) as num (num)}
      <li class="slide" data-blossom-slide>{num}</li>
    {/each}
  </BlossomCarousel>
  <div class="controls">
    <BlossomPrev forId="my-carousel" />
    <BlossomDots forId="my-carousel">
      {#snippet children({ index, active })}
        <BlossomDot class="dot" data-active={active}>
          <img src="https://placehold.co/40x40" alt="Image {index + 1}" />
        </BlossomDot>
      {/snippet}
    </BlossomDots>
    <BlossomNext forId="my-carousel" />
  </div>
</div>

// packages/vue/src/App.vue
<script setup>
import BlossomCarousel from "./BlossomCarousel.vue";
import BlossomPrev from "./BlossomPrev.vue";
import BlossomNext from "./BlossomNext.vue";
import BlossomDots from "./BlossomDots.vue";
import BlossomDot from "./BlossomDot.vue";
</script>

<template>
  <div class="page">
    <h1>Blossom Vue</h1>
    <BlossomCarousel id="my-carousel" class="carousel">
      <ul class="track">
        <li v-for="i in 12" :key="`slide${i}`" class="slide" data-blossom-slide>
          {{ i }}
        </li>
      </ul>
    </BlossomCarousel>
    <div class="controls">
      <BlossomPrev for="my-carousel" />
      <BlossomDots for="my-carousel">
        <template #default="{ index, active }">
          <BlossomDot :data-active="active" :aria-label="`Go to image ${index + 1}`">
            <img src="https://placehold.co/40x40" />
          </BlossomDot>
        </template>
      </BlossomDots>
      <BlossomNext for="my-carousel" />
    </div>
  </div>
</template>

<style scoped>
.page {
  height: 100vh;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}

.carousel {
  scroll-padding-inline: 1rem;
  scroll-snap-type: x mandatory;
  scroll-snap-stop: always;

  padding-block: 4rem;
  margin-block: -4rem;
}

.track {
  display: grid;
  grid-auto-flow: column;
  grid-auto-columns: 300px;
  grid-gap: 1rem;
  padding-inline: 30vw;
  width: fit-content;
}

.slide {
  width: 100%;
  aspect-ratio: 3/4;
  border-radius: 1rem;
  background-color: #404040;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  scroll-snap-align: center;

  &:nth-child(odd) {
    aspect-ratio: auto;
    grid-column: span 2;
  }
}

.controls {
  display: flex;
  gap: 1rem;
  align-items: center;
  margin-block-start: 1.5rem;
}

.dot {
  opacity: 0.4;

  &[data-active="true"] {
    opacity: 1;
  }
}
</style>
