// packages/svelte/src/components/BlossomCarousel.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import { Blossom } from '@blossom-carousel/core';

  export let as = 'div';
  export let repeat = false;
  let root;
  let blossom;

  onMount(() => {
    blossom = Blossom(root, { repeat });
    blossom.init();
  });

  onDestroy(() => {
    blossom?.destroy();
  });
</script>

<svelte:element
  this={as}
  bind:this={root}
  blossom-carousel="true"
  {...$$restProps}
>
  <slot />
</svelte:element>

// packages/vue/src/BlossomCarousel.vue
<template>
  <component :is="is" ref="root" blossom-carousel="true">
    <slot />
  </component>
</template>

<script setup>
import { onMounted, onBeforeUnmount, shallowRef } from "vue";
import { Blossom } from "@blossom-carousel/core";

const props = defineProps({
  is: {
    type: String,
    default: "div",
  },
  repeat: {
    type: Boolean,
    default: false,
  },
});

const root = shallowRef(null);
defineExpose({ el: root });

let blossom = null;
onMounted(() => {
  blossom = Blossom(root.value);
  blossom.init();
});
onBeforeUnmount(() => {
  blossom.destroy();
});
</script>
