// packages/react/src/BlossomDots.tsx
import React, { type ReactNode } from "react";
import { COMMANDS } from "@blossom-carousel/navigation";
import DotScope from "./DotScope";
import { useNavigation } from "./useNavigation";

export interface BlossomDotsProps {
  for: string;
  children?: (props: { index: number; active: boolean }) => ReactNode;
}

const gotoPrefix = COMMANDS.gotoPrefix;

function usesCustomRender(
  render: BlossomDotsProps["children"],
): render is NonNullable<BlossomDotsProps["children"]> {
  if (!render) return false;
  const probe = render({ index: 0, active: false });
  return probe != null && typeof probe !== "boolean";
}

export default function BlossomDots({
  for: carouselId,
  children,
}: BlossomDotsProps) {
  const state = useNavigation(carouselId);
  const custom = usesCustomRender(children);

  return (
    <div data-blossom-dots role="group" aria-label="Choose slide to display">
      {custom
        ? Array.from({ length: state.count }, (_, index) => {
            const active = state.activeIndex === index;
            return (
              <DotScope
                key={index}
                index={index}
                active={active}
                forId={carouselId}
              >
                {children({ index, active })}
              </DotScope>
            );
          })
        : Array.from({ length: state.count }, (_, index) => (
            <button
              key={index}
              type="button"
              data-blossom-dot=""
              command={`${gotoPrefix}${index}`}
              commandfor={carouselId}
              aria-controls={carouselId}
              aria-current={state.activeIndex === index}
              aria-label={`Go to slide ${index + 1}`}
            >
              <span data-blossom-dot-marker="" />
            </button>
          ))}
    </div>
  );
}

// packages/vue/src/BlossomDots.vue
<script setup lang="ts">
import { Comment, toRef, type VNode } from "vue";
import { COMMANDS } from "@blossom-carousel/navigation";
import DotScope from "./DotScope.vue";
import { useNavigation } from "./useNavigation";

defineOptions({ inheritAttrs: false });

const props = defineProps<{ for: string }>();
const slots = defineSlots<{
  default?: (props: { index: number; active: boolean }) => VNode[];
}>();

const gotoPrefix = COMMANDS.gotoPrefix;
const state = useNavigation(toRef(props, "for"));

/** Slot exists even for comment-only content between tags; ignore those. */
function usesCustomSlot(): boolean {
  return (slots.default?.({ index: 0, active: false }) ?? []).some(
    (node) => node.type !== Comment,
  );
}
</script>

<template>
  <div data-blossom-dots role="group" aria-label="Choose slide to display">
    <template v-if="usesCustomSlot()">
      <DotScope
        v-for="(_, i) in state.count"
        :key="`dot-${i}`"
        :index="i"
        :active="state.activeIndex === i"
        :for-id="props.for"
      >
        <slot :index="i" :active="state.activeIndex === i" />
      </DotScope>
    </template>
    <template v-else>
      <button
        v-for="(_, i) in state.count"
        :key="`dot-${i}`"
        type="button"
        data-blossom-dot
        :command="`${gotoPrefix}${i}`"
        :commandfor="props.for"
        :aria-controls="props.for"
        :aria-current="state.activeIndex === i"
        :aria-label="`Go to slide ${i + 1}`"
      >
        <span data-blossom-dot-marker />
      </button>
    </template>
  </div>
</template>
