// packages/svelte/src/BlossomPrev.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { COMMANDS } from "@blossom-carousel/navigation";
  import { createNavigationStore } from "./navigation";

  export let forId: string;

  const state = createNavigationStore();
  $: state.connect(forId);
  onDestroy(() => state.disconnect());
</script>

<button
  blossom-prev
  type="button"
  command={COMMANDS.prev}
  commandfor={forId}
  disabled={!$state.canPrev}
  aria-controls={forId}
  aria-label="Previous slide"
>
  <slot>‹</slot>
</button>

<style>
  :where([blossom-prev]) {
    touch-action: manipulation;
  }
</style>

// packages/vue/src/BlossomPrev.vue
<template>
  <button
    blossom-prev
    type="button"
    :command="command"
    :commandfor="props.for"
    :disabled="!state.canPrev"
    :aria-controls="props.for"
    aria-label="Previous slide"
  >
    <slot>‹</slot>
  </button>
</template>

<script setup lang="ts">
import { toRef } from "vue";
import { COMMANDS } from "@blossom-carousel/navigation";
import { useNavigation } from "./useNavigation";

const props = defineProps<{ for: string }>();

const command = COMMANDS.prev;
const state = useNavigation(toRef(props, "for"));
</script>

<style scoped>
:where([blossom-prev]) {
  touch-action: manipulation;
}
</style>
